name = "play"
compatibility_date = "2024-09-06"

[build]
command = "npm install && npm install just && npx just build-wasm && npm run build"
destination = "dist/spa"

[build.environment_variables]
NODE_VERSION = "20"

[[build.environment_variables]]
name = "PNPM_VERSION"
value = "8"