# Cloudflare R2 configuration for app4.dog game-play
# Static site deployment using R2 bucket + custom domain

# Live environment R2 bucket (main branch)
[[r2_buckets]]
bucket_name = "gameplay-live"
binding = "GAME_ASSETS"
preview_bucket_name = "gameplay-live"

# Staging environment R2 bucket (next branch)  
[[r2_buckets]]
bucket_name = "gameplay-next"
binding = "GAME_ASSETS_NEXT"
preview_bucket_name = "gameplay-next"
